title: "MAGENTO GURU"
description: "HÖCHSTLEISTUNG ENTSTEHT DURCH LEIDENSCHAFT UND NICHT DURCH LEISTUNGSDRUCK ODER ANPASSUNGSDRUCK."
author:
  name: "MAGENTO GURU"
  email: "https://micha-barthel.de"
  url: "https://micha-barthel.de"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "MAGENTO GURU"
year : "2021"
